"""create gift table

Revision ID: a000597d862b
Revises: 
Create Date: 2020-11-20 13:43:43.166989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a000597d862b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giver', sa.String(length=15), nullable=True),
    sa.Column('gift_desc', sa.String(length=150), nullable=True),
    sa.Column('receiver', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_id'), 'gift', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_id'), table_name='gift')
    op.drop_table('gift')
    # ### end Alembic commands ###
