"""create gift table

Revision ID: d7aee313efc5
Revises: a000597d862b
Create Date: 2020-11-20 15:35:55.650728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7aee313efc5'
down_revision = 'a000597d862b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift', sa.Column('password', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift', 'password')
    # ### end Alembic commands ###
