# Generated by Django 3.1.3 on 2020-11-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201122_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='long',
        ),
        migrations.AlterField(
            model_name='gift',
            name='desc',
            field=models.CharField(max_length=120),
        ),
    ]
