# Generated by Django 3.1.3 on 2020-11-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201122_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='authr',
            new_name='author',
        ),
    ]
