# Generated by Django 3.1.3 on 2020-11-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_gift_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.CharField(default='0', max_length=12),
            preserve_default=False,
        ),
    ]
